# Generated by Django 2.1.7 on 2019-05-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_user', models.CharField(blank=True, max_length=32, null=True)),
                ('mtime', models.DateTimeField()),
                ('md5', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '文件表',
                'verbose_name': '文件表',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('port', models.IntegerField(default=22)),
                ('user', models.CharField(max_length=20)),
                ('passwd', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('keyfile', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('note', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '主机',
                'verbose_name': '主机',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('mysql_ip', models.CharField(default='', max_length=15, null=True, unique=True)),
                ('redis_ip', models.CharField(default='', max_length=15, null=True)),
                ('zook_ip', models.CharField(default='', max_length=15, null=True)),
                ('activemq_ip', models.CharField(default='', max_length=15, null=True)),
                ('es_ip', models.CharField(default='', max_length=15, null=True)),
                ('flowhys_ip', models.CharField(default='', max_length=15, null=True)),
                ('log_ip', models.CharField(default='', max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': '主机组',
                'verbose_name': '主机组',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.SmallIntegerField()),
                ('install_script', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '等级表',
                'verbose_name': '等级表',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField()),
                ('type', models.SmallIntegerField(choices=[(0, '安装'), (1, '更新')])),
                ('ip', models.CharField(max_length=15)),
                ('version_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('server_name', models.CharField(max_length=50)),
                ('level', models.SmallIntegerField()),
                ('state', models.SmallIntegerField(choices=[(0, '安装'), (1, '更新')])),
            ],
            options={
                'verbose_name_plural': '任务表',
                'verbose_name': '任务表',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_user', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '用户表',
                'verbose_name': '用户表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together={('ctime', 'ip', 'version_name', 'file_name')},
        ),
        migrations.AddField(
            model_name='files',
            name='version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iotmp.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('name', 'version')},
        ),
    ]
