# Generated by Django 2.1.7 on 2019-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='logfile',
            field=models.CharField(default='', max_length=50),
        ),
    ]
