# Generated by Django 2.1.7 on 2019-05-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotmp', '0002_tasks_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
