# Generated by Django 2.1.7 on 2019-05-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotmp', '0003_tasks_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='check_exp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='server',
            name='check_type',
            field=models.SmallIntegerField(choices=[(0, 'url'), (1, 'shell')], default=0),
        ),
    ]
