# Generated by Django 2.1.7 on 2019-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotmp', '0005_server_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=-1),
        ),
    ]
