# Generated by Django 2.1.7 on 2019-05-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotmp', '0006_auto_20190508_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostGroup',
        ),
    ]
