# Generated by Django 2.1.7 on 2019-05-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotmp', '0007_delete_hostgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
