# Generated by Django 2.1.7 on 2019-05-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotmp', '0008_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField()),
                ('type', models.SmallIntegerField(choices=[(0, '安装'), (1, '更新')])),
                ('ip', models.CharField(max_length=15)),
                ('version_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('server_name', models.CharField(max_length=50)),
                ('level', models.SmallIntegerField()),
                ('state', models.SmallIntegerField(choices=[(0, '安装'), (1, '更新')])),
                ('logfile', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': '任务表',
                'verbose_name': '任务表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together={('ctime', 'ip', 'version_name', 'file_name')},
        ),
    ]
